from dotenv import load_dotenv
from os import getenv

load_dotenv()


URL_MONGO = getenv("URL_MONGO")
DATABASE = getenv("DATABASE")
COLLECTION_USERS = getenv("COLLECTION_USERS")
COLLECTION_CHALLENGE_OVERVIEW = getenv("COLLECTION_CHALLENGE_OVERVIEW")
COLLECTION_CHALLENGES_HISTORY = getenv("COLLECTION_CHALLENGES_HISTORY")
COLLECTION_CHALLENGES_RANDOM = getenv("COLLECTION_CHALLENGES_RANDOM")
COLLECTION_CHALLENGES_RESPONSE = getenv("COLLECTION_CHALLENGES_RESPONSE")

SECRET_KEY = getenv("SECRET_KEY")
ALGORITHM = getenv("ALGORITHM")

LOGIN_DOCUMENTATION = getenv("LOGIN_DOCUMENTATION")
PASSWORD_DOCUMENTATION = getenv("PASSWORD_DOCUMENTATION")

SENDER_EMAIL = getenv("SENDER_EMAIL")
SENDER_PASSWORD = getenv("SENDER_PASSWORD")
SMTP_SERVER = getenv("SMTP_SERVER")
SMTP_PORT = getenv("SMTP_PORT")
